# .pages.yml — Pages CMS config for: lawyers, cases
# Images live in: src/images/

media:
  name: images
  label: Images
  input: src/images
  output: src/images
  path: ""
  extensions: [png, jpg, jpeg, webp, svg]

settings:
  content:
    merge: true

content:
  # ---------------------
  # LAWYERS
  # ---------------------
  - name: lawyers
    label: 律師
    type: collection
    path: src/content/lawyers
    filename: "{primary}.md"
    view:
      primary: name
      fields: [name, title, order]
      sort: [order]
    fields:
      - { name: name, label: 姓名, type: string, required: true }
      - { name: title, label: 職稱, type: string, required: true }
      - { name: bio, label: 簡介, type: text, required: true }
      - { name: order, label: 排序, type: number }

      - name: education
        label: 學歷
        type: string
        list: true

      - name: specialties
        label: 專長領域
        type: string
        list: true

      - name: experience
        label: 經歷
        type: string
        list: true

      - name: image
        label: 大頭照
        type: object
        fields:
          - name: url
            label: Image
            type: image
            options:
              media: images
              path: ""
          - { name: alt, label: Alt text, type: string }

      - { name: body, label: 詳細介紹, type: rich-text }

  # ---------------------
  # CASES
  # ---------------------
  - name: cases
    label: 實務案例
    type: collection
    path: src/content/cases
    filename: "{primary}.md"
    view:
      primary: title
      fields: [title, category, status, date]
      sort: [date]
      default:
        sort: date
        order: desc
    fields:
      - { name: title, label: 案件標題, type: string, required: true }
      - { name: category, label: 領域分類, type: string, required: true }
      - { name: summary, label: 案件摘要, type: text, required: true }
      - { name: status, label: 狀態, type: string }
      - { name: date, label: 日期, type: date }

      - name: highlights
        label: 案件重點
        type: string
        list: true

      - { name: body, label: 詳細內容, type: rich-text }
